### 회원가입
POST http://localhost:8080/api/v1/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password1234!",
  "phone": "01012345678",
  "nickname": "testuser"
}

### 로그인
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password1234!"


### 토큰 재발급
POST http://localhost:8080/api/v1/auth/reissue
Cookie: refreshToken=eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiIzMThhYjgzOC01NzJkLTRiOTgtYjk4ZS00N2U1ODA0N2FiZGYiLCJzdWIiOiIxIiwidG9rZW5UeXBlIjoiUkVGUkVTSCIsImlhdCI6MTc4MTY3NDA5MCwiZXhwIjoxNzgyMjc4ODkwfQ.XEOf01rybg0kFms7E96goKIA4fBErNEaSL4Yu3cGPrVBch-wcLkl7F5IpxiGmvheCBXaDT_JeIEGAbtiT242Qw

### 로그아웃
POST http://localhost:8080/api/v1/auth/logout
Cookie: refreshToken=eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJiODE2MDk3ZS1hZjFjLTQ0MDItYjk1NS1mNjhjNWY0MjU3OGEiLCJzdWIiOiIxIiwidG9rZW5UeXBlIjoiUkVGUkVTSCIsImlhdCI6MTc4MTY3NDEwOCwiZXhwIjoxNzgyMjc4OTA4fQ.CCpRE2YjP8dyCtyjHbfxV1rvOT_PquxkJuRZlCJw3i0HFryv7QE9k49rWyXsI-oX_7-4uy9yz5YDWE0-OAaxfA
